"""
Charts + write-up for the sensing-radius experiment (E8).

Reads results/radius.json (produced by radius.py) and writes
  results/plots/radius_tradeoff.png
  results/RADIUS.md
"""

from __future__ import annotations

import json
import os

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from experiments import RESULTS_DIR

PLOTS = os.path.join(RESULTS_DIR, "plots")


def _style():
    plt.rcParams.update({
        "figure.facecolor": "#FAF9F5",
        "axes.facecolor": "#FAF9F5",
        "axes.edgecolor": "#91918D",
        "axes.labelcolor": "#191919",
        "text.color": "#191919",
        "xtick.color": "#5F5E5A",
        "ytick.color": "#5F5E5A",
        "grid.color": "#E3DACC",
        "font.size": 9,
        "axes.grid": True,
        "grid.alpha": 0.6,
        "legend.frameon": False,
    })


def chart(d: dict) -> str:
    _style()
    t = d["table"]
    r = [row["radius_m"] for row in t]
    fig, ax = plt.subplots(1, 3, figsize=(11.2, 3.4))

    ax[0].plot(r, [row["mae_k0"] for row in t], "o-", color="#CC785C", label="no labels")
    ax[0].plot(r, [row["mae_k25"] for row in t], "o-", color="#6E8B5A", label="after 25 labels")
    ax[0].set_xlabel("sensing radius (m)")
    ax[0].set_ylabel("people-count error (people)")
    ax[0].set_title("Error grows with the question", fontsize=10)
    ax[0].legend()

    ax[1].plot(r, [100 * row["within1_k25"] for row in t], "o-", color="#4F6B87",
               label="after 25 labels")
    ax[1].plot(r, [100 * row["within1_k0"] for row in t], "o--", color="#91918D",
               label="no labels")
    ax[1].set_xlabel("sensing radius (m)")
    ax[1].set_ylabel("within ±1 person (%)")
    ax[1].set_title("Being right to within one person", fontsize=10)
    ax[1].legend()

    ax[2].plot(r, [100 * row["coverage_people"] for row in t], "o-", color="#D4A27F",
               label="people sampled directly")
    ax[2].plot(r, [100 * row["vehicle_recall"] for row in t], "s-", color="#5B7C99",
               label="vehicles caught")
    ax[2].set_xlabel("sensing radius (m)")
    ax[2].set_ylabel("%")
    ax[2].set_title("What the radios really see", fontsize=10)
    ax[2].legend()

    for a in ax:
        a.set_xscale("log")
        a.set_xticks(r)
        a.set_xticklabels(["%g" % x for x in r])
    fig.tight_layout()
    path = os.path.join(PLOTS, "radius_tradeoff.png")
    fig.savefig(path, dpi=160)
    plt.close(fig)
    return path


def write_markdown(d: dict, plot_path: str) -> str:
    t = d["table"]
    law = d["law"]

    def row_line(x):
        return ("| {r:g} m | {name} | {truth:.2f} | ±{fresh:.2f} | ±{cal:.2f} "
                "| {w1:.0f}% | {cov:.0f}% | {vrec:.0f}% |").format(
            r=x["radius_m"], name=_name(x["radius_m"]), truth=x["truth_people_mean"],
            fresh=x["mae_k0"], cal=x["mae_k25"], w1=100 * x["within1_k25"],
            cov=100 * x["coverage_people"], vrec=100 * x["vehicle_recall"])

    def lawget(dct, r):
        for key in ("R%g" % r, "R%.1f" % r, "R%.0f" % r):
            if key in dct:
                return dct[key]
        return float("nan")

    measured = {r: lawget(law["measured"], r) for r in (5, 10, 15, 20, 30, 45, 60, 90)}
    fitted = {r: lawget(law["fitted"], r) for r in (5, 10, 15, 20, 30, 45, 60, 90)}

    sw = d.get("switch", [])
    sw_lines = "\n".join(
        "| {a:g} m → {b:g} m | {u:.2f} | {s:.2f} | {rules:.2f} | {same:.2f} |".format(
            a=x["train_radius_m"], b=x["test_radius_m"], u=x["unscaled"],
            s=x["rescaled"], rules=x["rules_only"], same=x["same_radius"])
        for x in sw)

    md = f"""# The sensing radius: what it costs you

Generated by `validation/radius.py` + `radius_report.py`.
Reproduce with `python3 radius.py && python3 radius_report.py`.

## The question

The app answers *"how many people are within R metres?"*. R is a choice, and it is
not a free one: it trades absolute error against coverage, and past a point it stops
buying anything at all. This experiment measures that trade-off instead of guessing
it. Every number below is 10 simulated street scenes x 300 s, the shipping
estimator, truth = "targets whose distance to the phone is <= R at this instant".

![radius trade-off](plots/{os.path.basename(plot_path)})

## Accuracy per radius

| radius | name | people really there | error, no labels | error, 25 labels | within ±1 | crowd sampled directly | vehicles caught |
|---|---|---|---|---|---|---|---|
{chr(10).join(row_line(x) for x in t)}

Read the table in two directions:

* **Down the first columns** — every extra metre of radius costs accuracy. Absolute
  error roughly doubles from 5 m to 90 m, and the chance of being right to within one
  person falls from ~100% to ~52%. Asking about a bigger region is asking a harder
  question, not getting a better instrument.
* **Across to the last columns** — the fraction of the crowd the radios *sample
  directly* peaks at 30 m (18%) and then falls, because at 2.4 GHz a phone simply
  cannot hear another phone much beyond ~15 m. Beyond 30 m the count is inference,
  not measurement: the calibrated model extrapolates from the slice it can see.

Two non-monotonic details worth knowing. Vehicle detection *peaks at 15 m* (40%):
a car passing close gives a clean, fast, hyperbolic range curve, while a car 40 m
away gives you two or three noisy samples. And below 10 m the count is mostly
infrastructure — beacons, laptops, parked-car sensors — not people, which is why the
"crowd sampled directly" share collapses to 7% at 5 m even though the absolute error
is at its best.

## Two laws that came out of it

**The RF prior scales with the square root of the radius, not its area.**
The device-free Wi-Fi channel sees a volume set by where the access points are, not
by the radius you asked about. Sweeping the multiplier per radius gives
alpha(R) = (R/25)^**{law['exponent']:.3f}** (rms log residual {law['rms_log_resid']:.3f} over 8 radii):

| R | 5 | 10 | 15 | 20 | 30 | 45 | 60 | 90 |
|---|---|---|---|---|---|---|---|---|
| measured best | {measured[5]} | {measured[10]} | {measured[15]} | {measured[20]} | {measured[30]} | {measured[45]} | {measured[60]} | {measured[90]} |
| fitted | {fitted[5]:.2f} | {fitted[10]:.2f} | {fitted[15]:.2f} | {fitted[20]:.2f} | {fitted[30]:.2f} | {fitted[45]:.2f} | {fitted[60]:.2f} | {fitted[90]:.2f} |

**The learned correction needs a unit conversion.** The RLS model predicts an
absolute headcount, so its residual is in the units of whichever radius it was
trained at. Fitting RMS(residual) against R gives s(R) = (R/25)^**{d['residual_exponent']:.3f}**.
Divide the training residual by it, multiply the prediction by it, and labels become
portable between radii.

## Does calibration survive a radius change?

No — and that is worth knowing before you promise the user otherwise. Training 25
labels at one radius and evaluating at another:

| train → test | model, unscaled | model, rescaled by s(R) | no model (rules only) | model trained at the test radius |
|---|---|---|---|---|
{sw_lines}

In **every** pair we tested, carrying the old model across is worse than dropping it
and falling back to the physics baseline. The rescaling law helps a lot when you
*shrink* the radius (45→15 m: 1.52 → 1.11) and hurts when you *grow* it
(15→45 m: 1.57 → 2.08), because growing amplifies a correction whose features no
longer match. So the app's behaviour on a radius change is: keep the weights as a
warm start, drop trust to zero, re-earn it with labels at the new radius. Nothing the
user labelled is thrown away — the labels stay in the database and in the Accuracy
tab.

## Limits of these numbers

* Simulated scenes, not a field trial: 10 pedestrians, 5 vehicles and ~22 static
  beacons per 5-minute scene, one radio environment (`urban`, path-loss exponent
  2.9). The *shape* of the trade-off is physics and should hold; the absolute
  numbers will move with real hardware, real MAC-rotation rates and real clutter.
* "Crowd sampled directly" is measured against simulated people, ~86% of whom carry
  a discoverable BLE device. Real carry rates are place- and time-dependent, which is
  exactly what the calibration exists to absorb.
* Standing people are the weakest case: they are easily mistaken for infrastructure
  and are counted at reduced weight, so a still crowd is under-counted at every
  radius.
"""
    path = os.path.join(RESULTS_DIR, "RADIUS.md")
    with open(path, "w") as fh:
        fh.write(md)
    return path


def _name(r: float) -> str:
    return {5.0: "Arm's length", 10.0: "Room", 15.0: "Pavement", 20.0: "Frontage",
            30.0: "Street", 45.0: "Crossroads", 60.0: "Square", 90.0: "Horizon"}.get(r, "")


if __name__ == "__main__":
    d = json.load(open(os.path.join(RESULTS_DIR, "radius.json")))
    p = chart(d)
    m = write_markdown(d, p)
    print("wrote", p)
    print("wrote", m)
